# Site settings
title: Tamas Hudak
email: tamas@hudak-balogh.hu
description: "Software Engineer"
url: "https://tomhudak.github.io"
baseurl: ""
github-username: tomhudak
twitter-username: tamas_hudak
medium-username: tamashudak
linkedin-username: tamas-hudak

google_analytics: UA-213370930-1

exclude:
  - .devcontainer
  - .vscode

plugins:
  - jekyll-feed
  - jekyll-sitemap