# Site settings
title: Tamas Hudak
email: tamas@hudak-balogh.hu
description: "Software Engineer"
url: "https://tomhudak.github.io"
baseurl: ""
github-username: tomhudak
twitter-username: tamas_hudak
medium-username: tamashudak
linkedin-username: tamas-hudak

google_analytics: G-E3M29N1MHD

exclude:
  - .devcontainer
  - .vscode

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

image:
  path: /assets/summer.jpeg
  height: 192
  width: 192  